//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace L9_Task1_WCF_Conifg_Client.AccumulatorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccumulatorService.IAccumulatorService")]
    public interface IAccumulatorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccumulatorService/Add", ReplyAction="http://tempuri.org/IAccumulatorService/AddResponse")]
        void Add(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccumulatorService/Add", ReplyAction="http://tempuri.org/IAccumulatorService/AddResponse")]
        System.Threading.Tasks.Task AddAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccumulatorService/GetSum", ReplyAction="http://tempuri.org/IAccumulatorService/GetSumResponse")]
        int GetSum();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccumulatorService/GetSum", ReplyAction="http://tempuri.org/IAccumulatorService/GetSumResponse")]
        System.Threading.Tasks.Task<int> GetSumAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccumulatorServiceChannel : L9_Task1_WCF_Conifg_Client.AccumulatorService.IAccumulatorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccumulatorServiceClient : System.ServiceModel.ClientBase<L9_Task1_WCF_Conifg_Client.AccumulatorService.IAccumulatorService>, L9_Task1_WCF_Conifg_Client.AccumulatorService.IAccumulatorService {
        
        public AccumulatorServiceClient() {
        }
        
        public AccumulatorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccumulatorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccumulatorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccumulatorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Add(int value) {
            base.Channel.Add(value);
        }
        
        public System.Threading.Tasks.Task AddAsync(int value) {
            return base.Channel.AddAsync(value);
        }
        
        public int GetSum() {
            return base.Channel.GetSum();
        }
        
        public System.Threading.Tasks.Task<int> GetSumAsync() {
            return base.Channel.GetSumAsync();
        }
    }
}
